server:
  port: 5009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.25.100




aliyun:
  sms:
    accessKeyId: 11111
    accessKeySecret: 222222
    template_code: SMS_85735065
    sign_name: 33333