server:
  port: 8081
spring:
  application:
    name: tensquare-base
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.25.100:3306/tensquare_base?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
  jpa:
    show-sql: true
    database: mysql

