devtools:
  livereload:
    enabled: true #\u662F\u5426\u652F\u6301livereload
#    port: 35729
  restart:
    enabled: true #\u662F\u5426\u652F\u6301\u70ED\u90E8\u7F72

server:
  port: 5006
spring:
  application:
    name: tensquare-spit #\u6307\u5B9A\u670D\u52A1\u540D
  data:
    mongodb:
      host: 192.168.25.100
      database: spitdb
  redis:
    host: 192.168.25.100
    port: 6379