server: 
  port: 5008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.100:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.100
  rabbitmq:
    host: 192.168.25.100

jwt:
  config:
    key: ruipeng
    ttl: 360000
